version: '3.8'

services:
  database:
    build:
      context: .
    container_name: 'mysql-service'
    restart: 'always'
    command: 'mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci'
    ports:
      - '3306:3306'
    volumes:
      - './volume/data:/var/lib/mysql'
      # - './volume/my.cnf:/etc/mysql/conf.d/my.cnf'
      - './sandbox.sql:/docker-entrypoint-initdb.dker'
    environment:
      - MYSQL_DATABASE=sandbox

volumes:
  volume: